apiVersion: apps/v1
kind: Deployment
metadata:
 name: devops-app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: devops-app
 template:
  metadata:
   labels:
    app: devops-app
  spec:
   containers:
    - name: web
      image: devops-app:v1
      imagePullPolicy: Never
      ports:
       - containerPort: 80
