---
- name: Configuracion local para proyecto DevOps
  hosts: local
  become: true
  tasks: 
    - name: Instalar paquetes base
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: true

    - name: Crear carpeta de publicacion
      file:
        path: /opt/devops-shell-framework
        state: directory
        mode: '0755'

    - name: Copiar pagina generada
      copy:
        src: /home/vboxuser/app/app/devops-app-eventos/app.js
        dest: /opt/devops-shell-framework/app.js
        mode: '0644'
